#! /usr/bin/env bash

function _echo() {
	if [[ "$1" ]]; then
		echo "$1"
	else
		echo "Hello, world!"
	fi
}

function _request() {
	if [[ "$1" ]]; then
		python scripts/parser.py -u "$1"
	else
		python scripts/parser.py -u "www.python.org/"
	fi
}

function _search() {
	if [[ "$1" ]]; then
		python scripts/parser.py -s "$1"
	else
		python scripts/parser.py -s "Python"
	fi
}

fmt_help="  %-20s\t%-54s\n"
function _help() {
	echo "Description: HTTP, Caching and Content Negotiation."
	echo ""
	echo "Usage: go2web [OPTION] [URL/<search-term>]"
	printf "${fmt_help}" \
		"-h, --help, help" "Print this help." \
		"-u, --url, url" "Make an HTTP request to the specified URL and print the response." \
		"-s, --search, search" "Make an HTTP request to search the term using your favorite engine and prints top 10 results."
}

case "$#" in
0)
	_help
	;;
1)
	case "$1" in
	-h | --help | help)
		_help
		;;
	*)
		echo "Input error."
		exit 1
		;;
	esac
	;;
2)
	if [[ "$1" == "-e" || "$1" == "--echo" || "$1" == "echo" ]]; then
		_echo "$2"
	elif [[ "$1" == "-u" || "$1" == "--url" || "$1" == "url" ]]; then
		_request "$2"
	elif [[ "$1" == "-s" || "$1" == "--search" || "$1" == "search" ]]; then
		_search "$2"
	else
		echo "Input error."
		exit 1
	fi
	;;
*)
	echo "Input error, too many arguments"
	exit 1
	;;
esac
